server.port=8080
spring.application.name=learn-ai
# DashScope
spring.ai.dashscope.api-key=sk-3566bb7ecf20404ba9fbbd16db1ca564
spring.ai.dashscope.chat.options.model=qwen-max
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Elasticsearch
elasticsearch.host=localhost
elasticsearch.port=9200
elasticsearch.username=
elasticsearch.password=

# DeepSeek
deepseek.api-key=sk-fae84a1705cb40e980a2c832ba067f09
file.upload.path=./uploads
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-swallow-size=-1
